import { createApp } from 'vue';
import { createI18n } from 'vue-i18n';
import { createRouter, createWebHistory } from 'vue-router';
import App from './App.vue';
import axios from 'axios';

// Import components and views
import DashboardView from './views/DashboardView.vue';
import LoginView from './views/LoginView.vue';
import ItemListView from './views/ItemListView.vue';
import ItemDetailView from './views/ItemDetailView.vue';
import CategoryListView from './views/CategoryListView.vue';
import CategoryCreateView from './views/CategoryCreateView.vue';
import SubcategoryListView from './views/SubcategoryListView.vue';
import BrandListView from './views/BrandListView.vue';
import StockMovementListView from './views/StockMovementListView.vue';
import PurchaseListView from './views/PurchaseListView.vue';
import SaleListView from './views/SaleListView.vue';
import PurchaseCreateView from './views/PurchaseCreateView.vue';
import SaleCreateView from './views/SaleCreateView.vue';
import LoanListView from './views/LoanListView.vue';
import ReturnListView from './views/ReturnListView.vue';
import LoanCreateView from './views/LoanCreateView.vue';
import WarrantyListView from './views/WarrantyListView.vue';
import WarrantyCreateView from './views/WarrantyCreateView.vue';
import SettingsView from './views/SettingsView.vue';
import GuestLayout from './views/GuestLayout.vue';
import UserListView from './views/UserListView.vue';
import UserCreateView from './views/UserCreateView.vue';
import UserEditView from './views/UserEditView.vue';
import ImportExportView from './views/ImportExportView.vue';

// Set up axios defaults
axios.defaults.baseURL = '/api';

// Create router
const routes = [
  { path: '/', redirect: '/dashboard' },
  { path: '/login', name: 'Login', component: LoginView },
  { path: '/dashboard', name: 'Dashboard', component: DashboardView, meta: { requiresAuth: true } },
  { path: '/items', name: 'Items', component: ItemListView, meta: { requiresAuth: true } },
  { path: '/items/:id', name: 'ItemDetail', component: ItemDetailView, meta: { requiresAuth: true }, props: true },
  { path: '/categories', name: 'Categories', component: CategoryListView, meta: { requiresAuth: true } },
  { path: '/categories/create', name: 'CategoryCreate', component: CategoryCreateView, meta: { requiresAuth: true } },
  { path: '/subcategories', name: 'Subcategories', component: SubcategoryListView, meta: { requiresAuth: true } },
  { path: '/brands', name: 'Brands', component: BrandListView, meta: { requiresAuth: true } },
  { path: '/stock-movements', name: 'StockMovements', component: StockMovementListView, meta: { requiresAuth: true } },
  { path: '/purchases', name: 'Purchases', component: PurchaseListView, meta: { requiresAuth: true } },
  { path: '/purchases/create', name: 'PurchaseCreate', component: PurchaseCreateView, meta: { requiresAuth: true } },
  { path: '/sales', name: 'Sales', component: SaleListView, meta: { requiresAuth: true } },
  { path: '/sales/create', name: 'SaleCreate', component: SaleCreateView, meta: { requiresAuth: true } },
  { path: '/loans', name: 'Loans', component: LoanListView, meta: { requiresAuth: true } },
  { path: '/loans/create', name: 'LoanCreate', component: LoanCreateView, meta: { requiresAuth: true } },
  { path: '/returns', name: 'Returns', component: ReturnListView, meta: { requiresAuth: true } },
  { path: '/warranties', name: 'Warranties', component: WarrantyListView, meta: { requiresAuth: true } },
  { path: '/warranties/create', name: 'WarrantyCreate', component: WarrantyCreateView, meta: { requiresAuth: true } },
  { path: '/settings', name: 'Settings', component: SettingsView, meta: { requiresAuth: true } },
  { path: '/guest', name: 'Guest', component: GuestLayout },
  { path: '/users', name: 'Users', component: UserListView, meta: { requiresAuth: true } },
  { path: '/users/create', name: 'UserCreate', component: UserCreateView, meta: { requiresAuth: true } },
  { path: '/users/:id/edit', name: 'UserEdit', component: UserEditView, meta: { requiresAuth: true }, props: true },
  { path: '/import-export', name: 'ImportExport', component: ImportExportView, meta: { requiresAuth: true } },
];

const router = createRouter({
  history: createWebHistory(),
  routes
});

// Navigation guard
router.beforeEach((to, from, next) => {
  const token = localStorage.getItem('token');
  
  if (to.meta.requiresAuth && !token) {
    next('/login');
  } else if (to.name === 'Login' && token) {
    next('/dashboard');
  } else {
    next();
  }
});

// Create i18n instance with messages
const i18n = createI18n({
  legacy: false, // Use Composition API
  locale: localStorage.getItem('locale') || 'en',
  fallbackLocale: 'en',
  messages: {
    en: {
      dashboard: 'Dashboard',
      inventory: 'Inventory',
      finance: 'Finance',
      stock: 'Stock',
      purchases: 'Purchases',
      sales: 'Sales',
      loans: 'Loans',
      returns: 'Returns',
      warranties: 'Warranties',
      settings: 'Settings',
      users: 'Users',
      items: 'Items',
      categories: 'Categories',
      subcategories: 'Subcategories',
      brands: 'Brands',
      reports: 'Reports',
      create: 'Create',
      edit: 'Edit',
      delete: 'Delete',
      save: 'Save',
      update: 'Update',
      cancel: 'Cancel',
      view: 'View',
      search: 'Search',
      reset: 'Reset',
      name: 'Name',
      email: 'Email',
      password: 'Password',
      confirm_password: 'Confirm Password',
      description: 'Description',
      price: 'Price',
      quantity: 'Quantity',
      category: 'Category',
      subcategory: 'Subcategory',
      brand: 'Brand',
      image: 'Image',
      status: 'Status',
      date: 'Date',
      total: 'Total',
      notes: 'Notes',
      borrower: 'Borrower',
      condition: 'Condition',
      terms: 'Terms',
      start_date: 'Start Date',
      end_date: 'End Date',
      supplier: 'Supplier',
      customer: 'Customer',
      phone: 'Phone',
      address: 'Address',
      success_message: 'Operation completed successfully',
      error_message: 'An error occurred',
      delete_confirmation: 'Are you sure you want to delete this item?',
      required_field: 'This field is required',
      role: 'Role',
      superadmin: 'Super Admin',
      admin: 'Admin',
      user: 'User',
      active: 'Active',
      inactive: 'Inactive',
      loaned: 'Loaned',
      returned: 'Returned',
      overdue: 'Overdue',
      expired: 'Expired',
      claimed: 'Claimed',
      stock_in: 'Stock In',
      stock_out: 'Stock Out',
      purchase: 'Purchase',
      sale: 'Sale',
      item_code: 'Item Code',
      item_name: 'Item Name',
      warranty_number: 'Warranty Number',
      purchase_number: 'Purchase Number',
      sale_number: 'Sale Number',
      loan_date: 'Loan Date',
      return_date: 'Return Date',
      current_stock: 'Current Stock',
      specifications: 'Specifications',
      stock_movements: 'Stock Movements',
      type: 'Type',
      reference: 'Reference',
      all: 'All',
      showing: 'Showing',
      of: 'of',
      previous: 'Previous',
      next: 'Next',
      create_stock_movement: 'Create Stock Movement',
      stock_level: 'Stock Level',
      quantity_sold: 'Quantity Sold',
      sales_trend: 'Sales Trend',
      top_selling_items: 'Top Selling Items',
      stock_candlestick: 'Stock Candlestick',
      select_supplier: 'Select Supplier',
      select_customer: 'Select Customer',
      select_item: 'Select Item',
      purchase_items: 'Purchase Items',
      sale_items: 'Sale Items',
      add: 'Add',
      remove: 'Remove',
      completed: 'Completed',
      create_purchase: 'Create Purchase',
      create_sale: 'Create Sale',
      insufficient_stock: 'Insufficient stock available',
      not_returned: 'Not Returned',
      create_loan: 'Create Loan',
      create_warranty: 'Create Warranty',
      end_date_must_be_after_start_date: 'End date must be after start date',
      images: 'Images',
      no_images_available: 'No images available',
      details: 'Details',
      no_specifications: 'No specifications available',
      no_description: 'No description available',
      actions: 'Actions',
      back: 'Back',
      navbar_title: 'Navbar Title',
      hero_title: 'Hero Title',
      hero_description: 'Hero Description',
      features_title: 'Features Title',
      features_description: 'Features Description',
      feature1_title: 'Feature 1 Title',
      feature1_description: 'Feature 1 Description',
      feature2_title: 'Feature 2 Title',
      feature2_description: 'Feature 2 Description',
      feature3_title: 'Feature 3 Title',
      feature3_description: 'Feature 3 Description',
      feature4_title: 'Feature 4 Title',
      feature4_description: 'Feature 4 Description',
      products_title: 'Products Title',
      products_description: 'Products Description',
      company_name: 'Company Name',
      settings_updated_successfully: 'Settings updated successfully',
      home: 'Home',
      products: 'Products',
      about: 'About',
      contact: 'Contact',
      login: 'Login',
      view_products: 'View Products',
      contact_us: 'Contact Us',
      why_our_products: 'Why Our Products',
      features: 'Features',
      features_description: 'We provide the best tools for warehouse and finance management.',
      feature1_description: 'Track all your inventory in real-time with our intuitive dashboard.',
      feature2_description: 'Monitor your finances with detailed reports and analytics.',
      feature3_description: 'Our platform is designed with the user in mind for maximum efficiency.',
      feature4_description: 'Your data is protected with enterprise-grade security features.',
      featured_products: 'Featured Products',
      featured_products_description: 'Check out our featured products below.',
      no_image: 'No Image',
      stock: 'Stock',
      view_details: 'View Details',
      no_products_available: 'No products available',
      all_rights_reserved: 'All rights reserved',
      create_category: 'Create Category',
      parent_category: 'Parent Category',
      no_parent: 'No Parent',
      create_user: 'Create User',
      edit_user: 'Edit User',
      passwords_do_not_match: 'Passwords do not match',
      leave_blank_to_keep_current: 'Leave blank to keep current',
      cannot_delete_yourself: 'You cannot delete yourself',
      import_export: 'Import/Export',
      import_data: 'Import Data',
      export_data: 'Export Data',
      select_import_type: 'Select Import Type',
      select_export_type: 'Select Export Type',
      select_file: 'Select File',
      download_template: 'Download Template',
      import: 'Import',
      export: 'Export',
      date_range: 'Date Range',
      export_format: 'Export Format',
      completed: 'Completed',
      import_completed_successfully: 'Import completed successfully',
      import_failed: 'Import failed',
      export_failed: 'Export failed',
      please_select_a_file: 'Please select a file',
      template_download_instruction: 'Template download would be implemented here',
      errors_found: 'Errors found',
    },
    id: {
      dashboard: 'Dasbor',
      inventory: 'Inventaris',
      finance: 'Keuangan',
      stock: 'Stok',
      purchases: 'Pembelian',
      sales: 'Penjualan',
      loans: 'Peminjaman',
      returns: 'Pengembalian',
      warranties: 'Garansi',
      settings: 'Pengaturan',
      users: 'Pengguna',
      items: 'Barang',
      categories: 'Kategori',
      subcategories: 'Subkategori',
      brands: 'Merek',
      reports: 'Laporan',
      create: 'Buat',
      edit: 'Edit',
      delete: 'Hapus',
      save: 'Simpan',
      update: 'Perbarui',
      cancel: 'Batal',
      view: 'Lihat',
      search: 'Cari',
      reset: 'Atur Ulang',
      name: 'Nama',
      email: 'Email',
      password: 'Kata Sandi',
      confirm_password: 'Konfirmasi Kata Sandi',
      description: 'Deskripsi',
      price: 'Harga',
      quantity: 'Jumlah',
      category: 'Kategori',
      subcategory: 'Subkategori',
      brand: 'Merek',
      image: 'Gambar',
      status: 'Status',
      date: 'Tanggal',
      total: 'Total',
      notes: 'Catatan',
      borrower: 'Peminjam',
      condition: 'Kondisi',
      terms: 'Ketentuan',
      start_date: 'Tanggal Mulai',
      end_date: 'Tanggal Akhir',
      supplier: 'Pemasok',
      customer: 'Pelanggan',
      phone: 'Telepon',
      address: 'Alamat',
      success_message: 'Operasi berhasil diselesaikan',
      error_message: 'Terjadi kesalahan',
      delete_confirmation: 'Apakah Anda yakin ingin menghapus item ini?',
      required_field: 'Bidang ini wajib diisi',
      role: 'Peran',
      superadmin: 'Super Admin',
      admin: 'Admin',
      user: 'Pengguna',
      active: 'Aktif',
      inactive: 'Tidak Aktif',
      loaned: 'Dipinjam',
      returned: 'Dikembalikan',
      overdue: 'Terlambat',
      expired: 'Kadaluarsa',
      claimed: 'Diklaim',
      stock_in: 'Stok Masuk',
      stock_out: 'Stok Keluar',
      purchase: 'Pembelian',
      sale: 'Penjualan',
      item_code: 'Kode Barang',
      item_name: 'Nama Barang',
      warranty_number: 'Nomor Garansi',
      purchase_number: 'Nomor Pembelian',
      sale_number: 'Nomor Penjualan',
      loan_date: 'Tanggal Pinjam',
      return_date: 'Tanggal Kembali',
      current_stock: 'Stok Saat Ini',
      specifications: 'Spesifikasi',
      stock_movements: 'Pergerakan Stok',
      type: 'Jenis',
      reference: 'Referensi',
      all: 'Semua',
      showing: 'Menampilkan',
      of: 'dari',
      previous: 'Sebelumnya',
      next: 'Selanjutnya',
      create_stock_movement: 'Buat Pergerakan Stok',
      stock_level: 'Tingkat Stok',
      quantity_sold: 'Jumlah Terjual',
      sales_trend: 'Tren Penjualan',
      top_selling_items: 'Item Terlaris',
      stock_candlestick: 'Grafik Stok',
      select_supplier: 'Pilih Pemasok',
      select_customer: 'Pilih Pelanggan',
      select_item: 'Pilih Barang',
      purchase_items: 'Item Pembelian',
      sale_items: 'Item Penjualan',
      add: 'Tambah',
      remove: 'Hapus',
      completed: 'Selesai',
      create_purchase: 'Buat Pembelian',
      create_sale: 'Buat Penjualan',
      insufficient_stock: 'Stok tidak mencukupi',
      not_returned: 'Belum Dikembalikan',
      create_loan: 'Buat Peminjaman',
      create_warranty: 'Buat Garansi',
      end_date_must_be_after_start_date: 'Tanggal akhir harus setelah tanggal mulai',
      images: 'Gambar',
      no_images_available: 'Tidak ada gambar tersedia',
      details: 'Detail',
      no_specifications: 'Tidak ada spesifikasi tersedia',
      no_description: 'Tidak ada deskripsi tersedia',
      actions: 'Aksi',
      back: 'Kembali',
      navbar_title: 'Judul Navbar',
      hero_title: 'Judul Hero',
      hero_description: 'Deskripsi Hero',
      features_title: 'Judul Fitur',
      features_description: 'Deskripsi Fitur',
      feature1_title: 'Judul Fitur 1',
      feature1_description: 'Deskripsi Fitur 1',
      feature2_title: 'Judul Fitur 2',
      feature2_description: 'Deskripsi Fitur 2',
      feature3_title: 'Judul Fitur 3',
      feature3_description: 'Deskripsi Fitur 3',
      feature4_title: 'Judul Fitur 4',
      feature4_description: 'Deskripsi Fitur 4',
      products_title: 'Judul Produk',
      products_description: 'Deskripsi Produk',
      company_name: 'Nama Perusahaan',
      settings_updated_successfully: 'Pengaturan berhasil diperbarui',
      home: 'Beranda',
      products: 'Produk',
      about: 'Tentang',
      contact: 'Kontak',
      login: 'Masuk',
      view_products: 'Lihat Produk',
      contact_us: 'Hubungi Kami',
      why_our_products: 'Mengapa Produk Kami',
      features: 'Fitur',
      features_description: 'Kami menyediakan alat terbaik untuk manajemen gudang dan keuangan.',
      feature1_description: 'Lacak semua inventaris Anda secara real-time dengan dasbor intuitif kami.',
      feature2_description: 'Pantau keuangan Anda dengan laporan dan analitik terperinci.',
      feature3_description: 'Platform kami dirancang dengan mempertimbangkan pengguna untuk efisiensi maksimal.',
      feature4_description: 'Data Anda dilindungi dengan fitur keamanan kelas perusahaan.',
      featured_products: 'Produk Unggulan',
      featured_products_description: 'Lihat produk unggulan kami di bawah ini.',
      no_image: 'Tidak Ada Gambar',
      stock: 'Stok',
      view_details: 'Lihat Detail',
      no_products_available: 'Tidak ada produk tersedia',
      all_rights_reserved: 'Hak cipta dilindungi',
      create_category: 'Buat Kategori',
      parent_category: 'Kategori Induk',
      no_parent: 'Tidak Ada Induk',
      create_user: 'Buat Pengguna',
      edit_user: 'Edit Pengguna',
      passwords_do_not_match: 'Kata sandi tidak cocok',
      leave_blank_to_keep_current: 'Biarkan kosong untuk mempertahankan yang saat ini',
      cannot_delete_yourself: 'Anda tidak dapat menghapus diri sendiri',
      import_export: 'Impor/Ekspor',
      import_data: 'Impor Data',
      export_data: 'Ekspor Data',
      select_import_type: 'Pilih Jenis Impor',
      select_export_type: 'Pilih Jenis Ekspor',
      select_file: 'Pilih Berkas',
      download_template: 'Unduh Template',
      import: 'Impor',
      export: 'Ekspor',
      date_range: 'Rentang Tanggal',
      export_format: 'Format Ekspor',
      completed: 'Selesai',
      import_completed_successfully: 'Impor berhasil diselesaikan',
      import_failed: 'Impor gagal',
      export_failed: 'Ekspor gagal',
      please_select_a_file: 'Silakan pilih berkas',
      template_download_instruction: 'Unduhan template akan diimplementasikan di sini',
      errors_found: 'Kesalahan ditemukan',
    }
  }
});

// Create and mount the app
const app = createApp(App);
app.use(router);
app.use(i18n);
app.mount('#app');